export const IMPORT_TEMPLATE_FIELDS = [
  'schema_version',
  'creditore_denominazione',
  'creditore_cf',
  'creditore_piva',
  'creditore_sede',
  'debitore_tipo',
  'debitore_denominazione_nome',
  'debitore_cf',
  'debitore_piva',
  'debitore_sede_residenza',
  'avvocato_nome',
  'avvocato_cf',
  'avvocato_foro',
  'avvocato_pec',
  'tribunale',
  'di_numero',
  'rg_numero',
  'di_data_emissione',
  'di_data_notifica',
  'flag_esecutorieta_nel_titolo',
  'di_data_esecutorieta',
  'capitale_ingiunto',
  'interessi_modalita',
  'interessi_tipo_tasso',
  'interessi_base_calcolo',
  'interessi_dies_a_quo',
  'interessi_data_finale',
  'interessi_clausola_testo'
] as const;

export function getImportTemplateRow() {
  return {
    schema_version: '1.0.0',
    creditore_denominazione: '',
    creditore_cf: '',
    creditore_piva: '',
    creditore_sede: '',
    debitore_tipo: '',
    debitore_denominazione_nome: '',
    debitore_cf: '',
    debitore_piva: '',
    debitore_sede_residenza: '',
    avvocato_nome: '',
    avvocato_cf: '',
    avvocato_foro: '',
    avvocato_pec: '',
    tribunale: '',
    di_numero: '',
    rg_numero: '',
    di_data_emissione: '',
    di_data_notifica: '',
    flag_esecutorieta_nel_titolo: 'NON_SO',
    di_data_esecutorieta: '',
    capitale_ingiunto: '',
    interessi_modalita: 'none',
    interessi_tipo_tasso: 'legale',
    interessi_base_calcolo: '',
    interessi_dies_a_quo: '',
    interessi_data_finale: '',
    interessi_clausola_testo: ''
  };
}
